Show vault details in the vault dropdown
pendulum-chain/portal pull request #155
Opened 2023-05-17 14:49 UTC by gonzamontiel

- I had to refactor the VaultSelector to use a Dropdown, because items cannot be customized with a simple select (LabelledSector)
- I didn't use the available DropdwonSelector because it assumes the value of the option is a simple string (we want a full custom item)
- **Important**: I used the value of issuedTokens of a measure of vault capacity, but this is probably not correct. Interlay defines vault capacity here: https://docs.interlay.io/#/vault/overview?id=fee-distribution-based-on-btc-capacity. Should we use this approach? We probably need some clarification here from @ebma

2023-05-17 14:51 UTC, gonzamontiel commented
BTW, I had to merge #139 to this branch to avoid some errors, so that PR is blocking this one.

2023-05-19 17:46 UTC, ebma commented
@gonzamontiel the deploy seems to have failed, can you look into that?

2023-05-22 08:09 UTC, ebma reviewed
I already mentioned it on Slack but I'll say it here again. 

Since we want to show the user how many tokens he can issue with each vault and not how many tokens the vault has issued _so far_ we cannot use `vault.issuedTokens`. Instead we should use the return values of [these two](https://github.com/pendulum-chain/spacewalk/blob/befd6fe8de903407e212902956398df25b50e8f3/pallets/vault-registry/rpc/src/lib.rs#L56C1-L66) RPC functions to receive the amounts of tokens that can be issued/redeemed with the current values of the vault collateral and price info.

2023-05-24 09:06 UTC, gonzamontiel commented
> @gonzamontiel the deploy seems to have failed, can you look into that?

Sorry, I was missing one commit from last week. I merge changes from #159 here, so I can show the issuable tokens in the vaults dropdown.

2023-05-24 12:48 UTC, ebma requested changes
The dropdown looks nice but as a user I would expect the dropdown to close once I click on an item to select it. Also, the amounts shown are always 0.00 which is probably a bug.

2023-05-24 15:09 UTC, gonzamontiel commented
> > The dropdown looks nice but as a user I would expect the dropdown to close once I click on an item to select it. Also, the amounts shown are always 0.00 which is probably a bug.
> 
> We need #159 merged to have this fully working.

It can be functional tested now. I also found annoying that the dropdown does not close automatically when selecting a item, apparently this is intentional in Daisy UI, I'm working on a fix (not that straight forward though)

2023-05-24 15:20 UTC, ebma approved these changes
Added two comments for minor issues but LGTM overall 👍

2023-05-24 15:20 UTC, ebma commented on src/helpers/spacewalk.ts
> +    throw Error('Asset has invalid characters');
Is this a regression from merging?

2023-05-24 15:20 UTC, ebma commented on src/helpers/spacewalk.ts
> +}
Can be removed probably

2023-05-24 15:46 UTC, gonzamontiel commented on src/helpers/spacewalk.ts
> +    throw Error('Asset has invalid characters');
bad merge, yes

2023-05-24 15:46 UTC, merged