Fix wrong parameter used for deriving a vault's Stellar address
pendulum-chain/portal pull request #168
Opened 2023-05-30 13:59 UTC by ebma

Fixes [this](https://github.com/pendulum-chain/tasks/issues/65) issue.

I changed the namings in the dialog a bit to make it clearer which address/account ID belongs to which network (Stellar vs parachain).

2023-05-30 14:06 UTC, ebma commented
I noticed that I actually still have to change something about 'destination address' vs 'vaults stellar address' because they are not necessarily the same although it's now shown like that.

2023-05-30 14:14 UTC, gonzamontiel commented
> I noticed that I actually still have to change something about 'destination address' vs 'vaults stellar address' because they are not necessarily the same although it's now shown like that.

So I should wait for reviewing?

2023-05-30 14:21 UTC, ebma commented
> So I should wait for reviewing?


Yes, please @gonzamontiel. I'll ping you again. Sorry for that, only realized that after creating the PR.

2023-05-30 17:01 UTC, ebma commented
Ready for review now @gonzamontiel

2023-05-31 09:03 UTC, gonzamontiel commented on src/pages/bridge/TransferDialog.tsx
> +import { useVaultRegistryPallet } from '../../hooks/spacewalk/vaultRegistry';
See my comment below
```suggestion
import { useVaultRegistryPallet } from '../../hooks/spacewalk/vaultRegistry';
import { toTitle } from '../../helpers/string';
```

2023-05-31 09:07 UTC, gonzamontiel requested changes
I like the changes! I only added a small suggestion and we can merge

2023-05-31 10:17 UTC, gonzamontiel approved these changes
lgtmrn

2023-05-31 10:17 UTC, merged