Update transfer dialogs design
pendulum-chain/portal pull request #295
Opened 2023-11-14 13:21 UTC by gonzamontiel

- [x] General dialog changes / refactor
- [x] Pendulum Completed Dialog
- [ ] Pendulum Cancelled Dialog
- [ ] Pendulum Pending Dialog
- [x] Amplitude Completed Dialog
- [ ] Amplitude Cancelled Dialog
- [ ] Amplitude Pending Dialog

2023-11-23 17:27 UTC, gonzamontiel commented
Somehow, after merging staging the styles in the branch are broken. Example: 
![Screenshot from 2023-11-23 18 23 18](https://github.com/pendulum-chain/portal/assets/4713407/b0b12a56-6c8c-4b26-931e-d73c891a7e6a)
The overlay doesn't show properly on the dialog. 
I'm trying to figure out the culprit.

2023-11-24 15:21 UTC, ebma requested changes
I know that it's phrased similarly in the designs but we should change the namings.

2023-11-24 15:21 UTC, ebma commented on src/pages/bridge/TransferDialog.tsx
> +                <div className="text-sm">Vault PEN Address ({tenantNameCapitalized})</div>
We should not call it PEN address. I would actually suggest we completely remove that and only call it `Vault Address ({tenant})`.

2023-11-24 15:21 UTC, ebma commented on src/pages/bridge/TransferDialog.tsx
> +                  <div className="text-sm">Vault PEN Address</div>
This is the vault's Stellar address and not a PEN address.

2023-11-28 10:22 UTC, ebma approved these changes
Looks good. But I noticed that something is wrong with the pop up for the active account in the top-right hand corner. It doesn't show properly anymore, not sure if this was introduced in this PR or another

To reproduce, connect to a wallet account and then click on your account in the top right corner. It will show a pop-up but it seems like it is placed above the button and not below it.

2023-11-28 11:25 UTC, merged

2024-03-15 14:15 UTC, ebma commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/pendulum-chain/portal/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: