chore: Update disclaimer Spacewalk bridge
pendulum-chain/portal pull request #394
Opened 2024-03-27 13:26 UTC by Sharqiewicz

### What:

Update disclaimer Spacewalk bridge

### How:

✅ Update disclaimer text

2024-03-27 14:13 UTC, prayagd requested changes
All good, Just one change in the third bullet i.e in "Total issuable amount (in USD)" please change number of 20000 USD to 50000 USD

2024-03-27 14:35 UTC, Sharqiewicz reviewed
Fixed

2024-03-27 14:44 UTC, annatekl approved these changes
good

2024-03-27 15:18 UTC, ebma commented on src/pages/bridge/Issue/index.tsx
> +          Estimated time for issuing: In a minute after submitting the Stellar payment to the vault, contact
How about we end the sentence here. 
```suggestion
          Estimated time for issuing: In a minute after submitting the Stellar payment to the vault. Contact
```

2024-03-28 05:16 UTC, prayagd commented on src/pages/bridge/Issue/index.tsx
> +          Estimated time for issuing: In a minute after submitting the Stellar payment to the vault, contact
Agree

2024-04-04 10:20 UTC, Sharqiewicz commented
✅ Ready @ebma

2024-04-04 10:33 UTC, ebma approved these changes

2024-04-05 07:15 UTC, prayagd approved these changes
Good to go

2024-04-05 09:47 UTC, merged