implement qr code in spacewalk bridge
pendulum-chain/portal pull request #442
Opened 2024-05-07 09:14 UTC by Sharqiewicz

### What:

Implement QR Code and Button compatible with Stellar SEP-0007 in order to allow user easily create transactions needed in Spacewalk.

### How:

Add package: qrcode.react - the most popular package for generating qr codes in React space
Create function: generateQRCodeAddress to easily create SEP-0007 URI scheme messages
Divide huge TransferDialog component into smaller ones
Implement SEP-0007 in ConfirmationDialog for Spacewalk > Issue and Redeem

### Comments:

Tested with wallets:
- Lobstr (mobile) ✅ works
- Solar (Desktop) ✅ works
- Rabet (Browser Extension) 🟥 doesn't work - Rabet doesn't listen for SEP-0007
- Freighter (Browser Extension) 🟥 doesn't work - Freighter doesn't listen for SEP-0007

Closes: #395

2024-05-10 11:35 UTC, ebma commented
## `yarn.lock` changes

<details open>
<summary>Click to toggle table visibility</summary>
<br/>

| Name | Status | Previous | Current |
| :- | :-: | :-: | :-: |
| `qrcode.react` | [<sub><img alt="ADDED" src="https://git.io/J38HP" height="16" /></sub>](#) | - | 3.1.0 |

</details>

2024-05-10 11:38 UTC, ebma commented
## `yarn.lock` changes

<details open>
<summary>Click to toggle table visibility</summary>
<br/>

| Name | Status | Previous | Current |
| :- | :-: | :-: | :-: |
| `qrcode.react` | [<sub><img alt="ADDED" src="https://git.io/J38HP" height="16" /></sub>](#) | - | 3.1.0 |

</details>

2024-05-13 16:28 UTC, ebma requested changes
Really nice changes, good job @Sharqiewicz 🙏 

Since we learned that the browser extensions don't support SEP-07 and 1) LOBSTR doesn't have a desktop wallet, 2) Solar does not fully support SEP-07 and 3) there don't seem to be any (popular) Stellar desktop wallets that support it, I think we should remove the extra 'Sign tx' button for now and re-add it as part of a new ticket. In this follow-up task we can then make the 'Sign tx' button trigger a signing request to the wallet browser extensions. 

Also, I think we should show at least a little helper text above the QR code so the user is not totally lost. I can imagine something like: 'Scan the QR code with a Stellar wallet'.

Besides that, the QR code scanning did not work for me on Amplitude/Foucoco. I assume it's because of the theme, showing a QR code **without a border** on a dark background. I assume this can be fixed by adding a little white border around the QR code.

2024-05-13 16:28 UTC, ebma commented on src/helpers/stellar/sep0007.ts
> +  issue_request_memo: string;
Nit: Let's continue using camelCase notation also for these fields.

2024-05-13 16:28 UTC, ebma commented on vite.config.ts
> +        // polyfillNode({}),
Do we need to remove this?

2024-05-16 10:27 UTC, ebma commented
## `yarn.lock` changes

<details open>
<summary>Click to toggle table visibility</summary>
<br/>

| Name | Status | Previous | Current |
| :- | :-: | :-: | :-: |
| `qrcode.react` | [<sub><img alt="ADDED" src="https://git.io/J38HP" height="16" /></sub>](#) | - | 3.1.0 |

</details>

2024-05-16 10:54 UTC, ebma commented
## `yarn.lock` changes

<details open>
<summary>Click to toggle table visibility</summary>
<br/>

| Name | Status | Previous | Current |
| :- | :-: | :-: | :-: |
| `qrcode.react` | [<sub><img alt="ADDED" src="https://git.io/J38HP" height="16" /></sub>](#) | - | 3.1.0 |

</details>

2024-05-16 10:54 UTC, ebma commented
## `yarn.lock` changes

<details open>
<summary>Click to toggle table visibility</summary>
<br/>

| Name | Status | Previous | Current |
| :- | :-: | :-: | :-: |
| `qrcode.react` | [<sub><img alt="ADDED" src="https://git.io/J38HP" height="16" /></sub>](#) | - | 3.1.0 |

</details>

2024-05-17 08:52 UTC, ebma approved these changes
Nice, can confirm it works also on Amplitude with the dark theme now 👍

2024-05-17 11:42 UTC, prayagd approved these changes
Works as expected, tested using Lobstr. Prefills with the vault address, amount and the memo. Really good work @Sharqiewicz

2024-05-21 04:57 UTC, prayagd commented
@Sharqiewicz is this done, can we merge?

2024-05-22 11:24 UTC, merged