Chore/improve paths
pendulum-chain/portal pull request #460
Opened 2024-05-24 09:03 UTC by Sharqiewicz

### What:

The paths in the app are just `strings` that can cause many problems, such as misspelling, pointing to a non-existent page (after renaming).

### How:

✅  Change the paths to be included in the `PATHS` enum. Enum is used for redirection throughout the application.
✅ Remove unused Stats page

2024-05-24 09:24 UTC, ebma requested changes
Nice changes 👍  The app seems broken though. If you open the deploy preview, you are not able to close the ToC dialog because the app is unresponsive, see the following error.

<img width="848" alt="image" src="https://github.com/pendulum-chain/portal/assets/6690623/f2cffdcd-368c-4b35-8fe6-994aca6d492d">

2024-05-24 09:24 UTC, ebma commented on src/app.tsx
> +  STAKING: 'staking',
```suggestion
  DASHBOARD: `${PATHS.DASHBOARD}`,
  GAS: `${PATHS.GAS}`,
  BRIDGE: `${PATHS.SPACEWALK}/${PATHS.BRIDGE}`,
  TRANSACTIONS: `${PATHS.SPACEWALK}/${PATHS.TRANSACTIONS}`,
  NABLA: `${PATHS.NABLA}`,
  NABLA_SWAP: `${PATHS.NABLA}/${PATHS.NABLA_SWAP}`,
  NABLA_SWAP_POOLS: `${PATHS.NABLA}/${PATHS.NABLA_SWAP_POOLS}`,
  NABLA_BACKSTOP_POOLS: `${PATHS.NABLA}/${PATHS.NABLA_BACKSTOP_POOLS}`,
  STAKING: `${PATHS.STAKING}`,
```

2024-05-24 09:24 UTC, ebma commented on src/pages/bridge/Issue/index.tsx
> +          navigateTo(`/${tenantName}${PAGES_PATHS.TRANSACTIONS}`);
```suggestion
          navigateTo(`/${tenantName}/${PAGES_PATHS.TRANSACTIONS}`);
```

2024-05-24 09:24 UTC, ebma commented on src/pages/bridge/Redeem/ConfirmationDialog.tsx
> +          navigateTo(`/${tenantName}${PAGES_PATHS.TRANSACTIONS}`);
```suggestion
          navigateTo(`/${tenantName}/${PAGES_PATHS.TRANSACTIONS}`);
```

2024-06-07 12:47 UTC, Sharqiewicz commented
@ebma I have implemented dynamic imports with dynamic paths using const pages = `import.meta.glob('./pages/**/index.tsx')`; from **ViteJS** ⚡ . This approach detects and registers all the files that match the specified pattern without fetching them immediately.

✨ Key Improvements:

- ✨ The directory structure for paths has been reorganized, making it more intuitive to create new page directories.
- ✨ The directories now match the paths configuration in app.tsx. For instance, the path `:network:/spacewalk/transactions` corresponds to `/pages/spacewalk/transactions/index.tsx`, which is automatically detected by `import.meta.glob` from ViteJS.
- ✨ All links in the app have been updated to use the `PATHS enum` from app.tsx, minimizing the risk of misspellings.

2024-06-11 16:10 UTC, ebma approved these changes
Cool, I like it 👌

2024-06-11 16:10 UTC, ebma commented on src/components/Layout/links.tsx
> +    link: '/spacewalk',
Should we also replace this link with something?

2024-06-11 16:10 UTC, ebma commented on src/components/Layout/links.tsx
> +    link: '/spacewalk',
As well as the nabla one in l. 96

2024-06-18 10:48 UTC, Sharqiewicz commented
@ebma changed ✅

2024-06-18 11:30 UTC, ebma approved these changes
LGTM

2024-06-18 11:30 UTC, merged