Remove 50% and Max from the Backstop pool withdraw UI
pendulum-chain/portal pull request #496
Opened 2024-06-10 12:38 UTC by Sharqiewicz

### What:

Remove 50% and Max from the Backstop pool withdraw UI

✅  Change color of Nabla dialog inputs
✅  Fix Nabla loading buttons styles
✅  Remove 50% and Max buttons
✅  Refactor Nabla modals to use reusable dialog components
✅  Add a space between Nabla Pool dialog asset and asset name ( Closes: #489 )

Closes: #478

2024-06-10 17:03 UTC, ebma requested changes
I can confirm that the change for https://github.com/pendulum-chain/portal/issues/489 is as expected.

For the '50%' and 'MAX' button, ticket https://github.com/pendulum-chain/portal/issues/478 specified that these should only be removed when withdrawing, not for depositing. So we should not remove them altogether but just hide them in these cases.

2024-06-26 11:49 UTC, Sharqiewicz commented
@ebma I have corrected what you asked for. Now when you click 50% or Max you may find that too many decimals are shown. This is corrected in PR #506 so there is no point in implementing it in this PR

2024-06-26 12:41 UTC, ebma reviewed
Works for swapping but the actions are now also missing for the deposit screen of the backstop pool which they should not.

<img width="1171" alt="image" src="https://github.com/pendulum-chain/portal/assets/6690623/ea39319d-ad4e-4304-8f24-633350fb52ff">

2024-06-26 12:41 UTC, ebma commented on src/components/Form/From/AvailableActions/index.tsx
> +  hideAvailable?: boolean;
I was confused when first reading it, let's maybe be more specific
```suggestion
  hideAvailableBalance?: boolean;
```

2024-06-26 14:01 UTC, Sharqiewicz commented
@ebma I've added for Backstop Pool Deposit and I changed the naming

2024-06-27 14:50 UTC, ebma approved these changes
Cool, works now 👍

2024-06-27 16:00 UTC, merged