Update disclaimer texts for Amplitude and Pendulum
pendulum-chain/portal pull request #538
Opened 2024-07-30 16:09 UTC by ebma

Updates the disclaimer texts shown in the issue dialog. 

Closes #458 and closes #459.

2024-07-31 10:19 UTC, Sharqiewicz approved these changes

2024-07-31 11:32 UTC, prayagd requested changes
@ebma 
- Is it possible to add a underline or make the colour of the support link darker to make it standout? I feel its not that clear that its clickable. This is for Pendulum, its perfect for Amplitude

2024-07-31 13:08 UTC, ebma commented
I changed it to a lighter color and italic font. Do you think it's better now @prayagd? Otherwise please tell me which color you'd prefer, it's not easy to find a good one 😅

2024-08-01 08:52 UTC, prayagd approved these changes
Good to go

2024-08-01 08:53 UTC, merged