feat: save global state to storage
pendulum-chain/portal pull request #71
Opened 2023-03-08 06:26 UTC by nejcm

A couple of notes on this: 
- needs to be tested from your side as state handling was a bit refactored
- an improvement would we to have an expiration date also
- I am not sure about security implications of this as we are storing the wallet address in storage. Now it is true that this is specific to the browser of the user where also the wallet is used/installed but would still like to do some research on this before going to prod with this.

2023-03-08 09:58 UTC, nejcm commented
Putting this into draft. Discovered a small issue that needs addressing

2023-03-09 17:35 UTC, gonzamontiel commented
Hey @nejcm , thanks for your PR. 

> A couple of notes on this:
> 
> * needs to be tested from your side as state handling was a bit refactored
> * an improvement would be to have an expiration date also
I thought based on the implementation in the [other PR](https://github.com/pendulum-chain/portal/pull/63) that this timeout mechanism was already there, it isn't the case?

> * I am not sure about security implications of this as we are storing the wallet address in storage. Now it is true that this is specific to the browser of the user where also the wallet is used/installed but would still like to do some research on this before going to prod with this.

Thanks for bringing this up. I believe we don't store any secret key for the user, since the accounts are managed by an extension (Talisman or PolkadotJS). These extensions ask for a password to securely store the address. How secure this is? Probably not ideal, but we are not less safe than the wallets we use.

> * note that the wallet info get stored in storage and the address is shown in the button but than the ss58Format comes in afterwards so the address changes in the button after 2-4s and that formatted one is not stored. Not sure how to fix this flicker
I will test this and come back to you, 2-4s is quite a lot.

2023-03-15 09:13 UTC, erasmus commented
@nejcm can I ask you to please connect your PRs with the issue? 🙏

2023-03-15 09:21 UTC, nejcm commented
it is connected. https://github.com/pendulum-chain/portal/issues/61

2023-03-15 17:40 UTC, nejcm commented
Merged staging

2023-03-21 13:15 UTC, gonzamontiel requested changes
So many unrelated lines are changed due to formatting. We better first agree on format to avodi conflicts.

2023-03-21 13:15 UTC, gonzamontiel commented on src/pages/collators/dialogs/ClaimRewardsDialog.tsx
> -            <h1 className="flex text-4xl">{format(amount, tokenSymbol, true)}</h1>
Hey @nejcm, do you have an auto formatter ? In that cases, which one? So we all agree in one with the same rules.
This causes that every single file is changed to a new format, leading to conflicts with lines that you didn't even touch. I can't approve this PR with so many unrelated lines changed

2023-03-21 13:19 UTC, nejcm commented
I have prettier which is included in the project with the relevant config. The only difference is that I have a config option set that it runs each time I save the file. So each file I change it will run it on the entire file. I believe the prettier was not run on the entire project yet since its inclusion.

2023-03-21 17:22 UTC, gonzamontiel commented
hey @nejcm , there are some conflicts due to recent changes on staging, hopefully after those everything will be smoother. Can you please fix them and then I'll approve! thanks :pray:

2023-03-22 16:25 UTC, gonzamontiel requested changes
hey @nejcm pls check that there are unresolved conflicts. Better would be to rebase the branch to staging.

2023-03-22 16:25 UTC, gonzamontiel commented on src/components/LabelledInputField/index.tsx.orig
> +<<<<<<< HEAD
Also another unresolved conflict.

2023-03-22 19:55 UTC, nejcm commented on src/assets/UnlinkIcon.tsx.orig
> +interface Props {
Missed it and did not delete the orig file

2023-03-23 15:20 UTC, gonzamontiel commented
Hey, there are quite a lot of orig files. Maybe it is better to create another, simple PR, with only the requested changes (save state to local storage). It is too hard to review at this point.

2023-03-24 03:58 UTC, nejcm commented
@gonzamontiel I believe all removed now

2023-03-29 12:44 UTC, gonzamontiel approved these changes

2023-03-31 14:29 UTC, merged